#!/usr/bin/env python3
"""Offline d1/final-frame analyzer for Japanese VC Blue Mewtwo SAFE traces.

No runtime hooks are added.  This consumes v7.3.2 SAFE mewtwo_trace CSVs and
extracts the GB-release phase sequence plus the two cycle-accurate d1 candidates.

Model facts:
- Wild DVs are generated by two consecutive BattleRandom calls.
- BattleRandom enters Random_ with carry=1 in a normal non-link battle.
- Random_ first->second rDIV reads are 44 T-cycles apart (<1 DIV tick).
- BattleRandom #1 first-rDIV -> #2 first-rDIV is 480 T-cycles = 1.875 DIV ticks,
  so d1 is exactly d2-1 or d2-2 modulo 256.
- The normal VBlank Random path uses carry-in 0 on PrepareOAMData's normal
  clear-loop return path.

The final d1 ambiguity is intentionally preserved unless extra phase evidence
selects one; this script never silently turns it into a false exact result.
"""
from __future__ import annotations

import argparse
import csv
import glob
from dataclasses import dataclass
from pathlib import Path


def h2(s: str) -> int:
    return int(s, 16) & 0xFF


def h4(s: str) -> int:
    return int(s, 16) & 0xFFFF


@dataclass
class Trace:
    path: Path
    meta: dict[str, str]
    rows: list[dict[str, str]]
    gb: dict[str, str]

    @property
    def by_seq(self) -> dict[int, dict[str, str]]:
        return {int(r["seq"]): r for r in self.rows}


def parse_trace(path: str | Path) -> Trace:
    p = Path(path)
    lines = p.read_text(encoding="utf-8-sig").splitlines()
    mh = next(csv.reader([lines[0]]))
    mv = next(csv.reader([lines[1]]))
    if not mh or mh[0] != "meta" or not mv or mv[0] != "MEWTWO":
        raise ValueError("not a Mewtwo trace")
    meta = dict(zip(mh[1:], mv[1:]))

    seq_i = next(i for i, line in enumerate(lines) if line.startswith("seq,rel,"))
    rows: list[dict[str, str]] = []
    for row in csv.DictReader(lines[seq_i:]):
        s = (row.get("seq") or "").strip()
        if not s.isdigit():
            break
        rows.append(row)

    gb: dict[str, str] = {}
    for i, line in enumerate(lines[:-1]):
        if line.startswith("gb_release_meta,"):
            gh = next(csv.reader([line]))
            gv = next(csv.reader([lines[i + 1]]))
            if gv and gv[0] in ("GBREL", "GB_RELEASE"):
                gb = dict(zip(gh[1:], gv[1:]))
            break
    if not gb:
        raise ValueError("gb_release_meta not found")
    return Trace(p, meta, rows, gb)


def adc_carry(a: int, b: int, cin: int) -> int:
    return int(a + b + cin > 0xFF)


def infer_random(a0: int, s0: int, a1: int, s1: int, cin: int):
    first = (a1 - a0 - cin) & 0xFF
    cout = adc_carry(a0, first, cin)
    second = (s0 - s1 - cout) & 0xFF
    gap = (second - first) & 0xFF
    return (first, second, gap) if gap in (0, 1) else None


def release_phases(t: Trace):
    by = t.by_seq
    start, pre = int(t.gb["seq"]), int(t.gb["pre_seq"])
    out = []
    for q in range(start, pre):
        a, b = by.get(q), by.get(q + 1)
        if not a or not b:
            continue
        r = infer_random(h2(a["rng_add"]), h2(a["rng_sub"]),
                         h2(b["rng_add"]), h2(b["rng_sub"]), 0)
        if r is None:
            continue
        first, second, gap = r
        div0, div1 = h2(a["div"]), h2(b["div"])
        out.append({
            "seq": q,
            "phase": (first - div0) & 0xFF,
            "gap": gap,
            "step": (div1 - div0) & 0xFF,
            "first": first,
            "second": second,
        })
    return out


def final_model(t: Trace):
    raw = h4(t.meta["raw_dv"])
    low, high = raw & 0xFF, raw >> 8
    pre_a, pre_s = h2(t.gb["pre_rng_add"]), h2(t.gb["pre_rng_sub"])
    pre_div = h2(t.gb["pre_div"])
    final_s = h2(t.meta["battle_rng_sub"])

    # BattleRandom #2: high = low + d2 + carry-in(1).
    d2 = (high - low - 1) & 0xFF
    candidates = []
    for ticks in (1, 2):
        d1 = (d2 - ticks) & 0xFF
        # BattleRandom #1: low = add_after_vblank + d1 + carry-in(1).
        add_after_vblank = (low - d1 - 1) & 0xFF
        # Normal VBlank Random carry-in is 0.
        vb1 = (add_after_vblank - pre_a) & 0xFF
        vb_carry = adc_carry(pre_a, vb1, 0)

        valid = []
        for vg in (0, 1):
            vb2 = (vb1 + vg) & 0xFF
            s1 = (pre_s - vb2 - vb_carry) & 0xFF
            c1 = adc_carry(add_after_vblank, d1, 1)
            for g1 in (0, 1):
                s2 = (s1 - ((d1 + g1) & 0xFF) - c1) & 0xFF
                c2 = adc_carry(low, d2, 1)
                for g2 in (0, 1):
                    s3 = (s2 - ((d2 + g2) & 0xFF) - c2) & 0xFF
                    if s3 == final_s:
                        valid.append((vg, g1, g2))
        candidates.append({
            "ticks": ticks,
            "d1": d1,
            "d2": d2,
            "vb1": vb1,
            "phase": (vb1 - pre_div) & 0xFF,
            "valid": valid,
        })
    return raw, d2, candidates


def report(t: Trace):
    phases = release_phases(t)
    raw, d2, cand = final_model(t)
    print(f"\n== {t.path.name} ==")
    print(f"raw={raw:04X} GBREL->DV={t.gb['release_to_battle']}F "
          f"GBREL_DIV={t.gb['div']} PRE_DIV={t.gb['pre_div']} d2={d2:02X}")
    print("release->pre VBlank phases:", " ".join(str(x["phase"]) for x in phases))
    print("release->pre rDIV gaps:     ", " ".join(str(x["gap"]) for x in phases))
    print("sample DIV steps:           ", " ".join(str(x["step"]) for x in phases))
    print("final-frame d1 candidates:")
    for c in cand:
        gaps = ",".join("".join(map(str, x)) for x in c["valid"]) or "-"
        print(f"  d1={c['d1']:02X}=d2-{c['ticks']}  finalVB={c['vb1']:02X} "
              f"phase=+{c['phase']} SUB={'OK' if c['valid'] else 'FAIL'} gaps={gaps}")
    return phases, cand


def expand(items: list[str]):
    out, seen = [], set()
    for item in items:
        matches = [Path(x) for x in glob.glob(item)] or [Path(item)]
        for p in sorted(matches):
            if p.exists() and p.resolve() not in seen:
                seen.add(p.resolve())
                out.append(p)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("traces", nargs="+")
    args = ap.parse_args()
    all_phases, all_final = [], []
    for p in expand(args.traces):
        try:
            phases, cand = report(parse_trace(p))
        except Exception as e:
            print(f"{p}: ERROR {e}")
            continue
        all_phases.append(phases)
        all_final.append([x["phase"] for x in cand])

    if all_phases:
        print("\n== aggregate release->pre phase envelope ==")
        for i in range(max(map(len, all_phases))):
            vals = [x[i]["phase"] for x in all_phases if i < len(x)]
            print(f"F{i+1}: {min(vals)}..{max(vals)} values={vals}")
        print("final-VBlank phase candidates:", all_final)
        print("d1 ambiguity intentionally preserved as d2-1 / d2-2")


if __name__ == "__main__":
    main()
