#!/usr/bin/env python3
from pathlib import Path
import json,zlib,base64,hashlib
P=Path('reader_core/src/crystal/practical.rs'); T=Path('reader_core/src/crystal/trace.rs')
EP='10c7850a60f01c92b0450cae9df3d2f8fd20731d9b23d8f1cc6df7b91399ed26'; ET='0d47182315188cd12fb6b8bccd818ab7bfe9426ab69f76585a7bf1161fadb391'
def sha(x): return hashlib.sha256(x.read_bytes()).hexdigest()
if sha(P)!=EP or sha(T)!=ET: raise SystemExit('v710 base mismatch')
def rep(x,a,b,n):
    if x.count(a)!=1: raise SystemExit(f'{n}: {x.count(a)}')
    return x.replace(a,b,1)
DATA_B85='c-rlp&vM%~5QpD|XB>!K{M9W@-y)Mk553kIw>@?8?p=xmu#!NNSWA=`>5|FV{KOG$VL$(Nfp7nHe|3i#RQKaYcj&%!^q=?cpnKK54PW?5UwD7}_n$wz1FG(i?(j`Vg<e^!yipO9rb{(MrHxnGS*3$f(1QZ#6<|<WO@PaQW`JXWCLk)Hm)2gPRn{mED$?usbUD!FhQ8$tA#{09uTL)x^x6q=3DFF34AB{(7Yzx(0t5yi1HuH1Z+rxfZ#)6E0Mi@qRrN^)_N1`oNu591H~}F6$be9NwDfPE0Gk2q8DQxWEI*3`_zVC8JOk)b(@#K5fMGynfXM)%IsvW#ngNahdISixAp^*OzyM4DB*3d^3t)Q&*bJBi#0=0~5E$SY0281S;21!6ad86ZE?^RX2?zy1280v9PJrt(U<=@T2GFGj2f!!-C%`iR7~nJD7!V6!7!Vm?CV)Vl0mlH%0G9we0ijp4;uHWG5HjEs02!dW(7KQTS{e#qC%_~iGJx(v>%s`oU1(vL0G9w=0LK8$0H;C%Fav=B$bi5AI{}*3tU}mA(8`bqV*QaYik7TGct!vt{6x4+3`<jFgkeNXL`Vdl5snc$69YUVHY4;&*Tb@PMCe8l84?oWGXf0prwA<&35f|Y42cY(PXsLy8PN%G1<?#~454d>MPfukMvx(aAy^PlbiWC)1))`<AhsaGLNOvy(HeF{=uWgu6vQ(GGNKdW7&5F?ks+oan2=BqWC-1fmWzVu2_ZHiwjlKBKSeMjkPy!hU<iFev@M89NGyn9NMs1zX;?HyL}$b?L^H${#45TUA+$h+zz}3eU<f7zGD3HvWg{b@XNb*+Nl0V}-HDctg7|{Cgy@2}GbA#^Bm^@O7(%Z&tRES18L<;`)TD&ijEtHT3gQz21@R04hGes%XF8e{uyVar-@mKw@4**G&$2Slf<@2z@IjnEyM_mG{_Gm8G)S%Vh)BHD$-ESWUfN5&)Jwh8NWE0cyc9%UIsjXGDPF@%ZHt$Bsh67MrP$=9R_3K3^3nkid8w0nDKak&Ena#mvRis7wt4BP$!_7LM<g($!AqUoOHuBnz1T~&)JsG5Qf%|mbCqrI(sPwv@1++iyN#FPr@eGQn!NN>WgEQoTxA=))XKdS=Dd`C3?tH#Igv5Gy?2N3Q;n%)oKnf(Qz{AbsbpB;G>hTfywhCB+{#q4CUYxN$-2xn+45E1xFEk>nMzh<ZdEFIDRZk*$(qcqNG0nsx0p)K$=ss-&B@$iD*3U@tx6>;GWSs`c_DLcsbp+QCF?S`m`cvc++r#@Cv%IbWL4(cQpq4oC2f=aRb8$vm7H_A<y5lna&z{#sB)`PNv3kEQpuXitxP2=Dz_??tg76qRB}e;8dJ$APbF(Aw=$K)wp4OK<vy~%ips4^C95jem`YlCDhcvbGPb3X^@wp*Dp^a`R;H4bWKEt*&V)4=spO3_uvhr^3jbDye{SpWua|~@;T8TpXZRO(6aJm(-z)rkobV6D;ooPP((WGNpV?FR=WY=GE$Lr#FBasz*jP2jma(%bm4qpk9M-Zimi#TnlKR6~@|Ml-vnp?;RUU*bzU5SCuF5-Ul}AyPH?k_PWmP^%tGty~`K457w#u)Fh32Zf`(%}eJ+%0Oyvkd7l?QQ^Uy}>ft9&o5^8OwzJ}s~EVP91qrB%KcxA?rg%HL<=YU_OfZrgnTJBnQ3$s-qf>?6?jSNzPd<lOI8Tl*L0eDUgA6>!U~3R<>RAxO6>Sm{;;*vVD}zn`rNbMklFtqRv@3VLZ%(8!yDzxq}MD<28lYg2H$tqNMcRUyc?Dp=uGg{w?x1?hyAeNAY+CbSx|xE5bLsqYt|q(0lh?WRofOUWcn!>DBC*K75t<o)*8p}cVIqMdQqJ$B7O2T0o)@h<I*U!icdj22(J7qOynp|o)IdnjD?sS4LCMY!W=@h(z?>x>qoc(iy2DMG)|Xfgc^Mx<@m{Kc^3ZPxYGeJ&&Kb7^s(YqR-h*na-m$)gSwM;#~nXT*IjEA4ZEu+P;z{|w^!=lh>5;6<IT8~<r}CV;S?;bPpj)1_sduCVcN@oVhps>8+4F?J*zF80!~BO@L=(z_lzT6V^2O}|Jc&H1?GWilx_S~6~Tv}BNtlsr??qGd@-*fwbaVbaoegbzrMmb^mJVr5Co#+$f*{dtXTH*xDHNm@R!iMxN2d5tS=;(q*jjsCTX`yuBwuDpr+VUL!4fbC4L1J7Rvo^NZVw>wz!^9P>eJ`OzJ-b#bC|M$=bOWygwbMqtzp5JAP_<4r0aQg$#cQ=f6wSy($=lA~sj2ZlS'
D=json.loads(zlib.decompress(base64.b85decode(DATA_B85)).decode())
def tab(raw,end): return [sum(((b+x)&255) for x in raw[:end+1]) for b in range(256)]
def arr(n,v): return 'const '+n+':[u32;256]=['+','.join(map(str,v))+'];\n'
r='''\n// v7.1 recent Exact-2F empirical PRE-conditioned branches.\nconst EMP_FIRST_ID:u8=101; const EMP_COUNT:usize=5;\n#[derive(Clone,Copy)] struct EmpLane{id:u8,source:u16,pre_proto:u8,pre_rot:u8,post_proto:u8,post_rot:u8,route:u8,full_a:&'static[u32;256],full_s:&'static[u32;256],p40_a:&'static[u32;256],p40_s:&'static[u32;256],p716_a:&'static[u32;256],p716_s:&'static[u32;256],o40a:u8,o40s:u8,o716a:u8,o716s:u8,o717a:u8,o717s:u8,last_a:u8,last_s:u8}\nconst EMP_R4_A:[u8;4]=[183,185,191,193]; const EMP_R4_S:[u8;4]=[183,186,191,193];\n'''
for i,d in enumerate(D,1):
    for n,raw,end in [('FA',d['a'],729),('FS',d['s'],729),('A40',d['a'],40),('S40',d['s'],40),('A716',d['a'],716),('S716',d['s'],716)]: r+=arr(f'E{i}_{n}',tab(raw,end))
r+='const EMP_LANES:[EmpLane;EMP_COUNT]=[\n'
for i,d in enumerate(D,1):
    a=d['a'];s=d['s'];r+=f"EmpLane{{id:{100+i},source:{d['n']},pre_proto:b'{d['pp']}',pre_rot:{d['pr']},post_proto:b'{d['op']}',post_rot:{d['or']},route:{d['route']},full_a:&E{i}_FA,full_s:&E{i}_FS,p40_a:&E{i}_A40,p40_s:&E{i}_S40,p716_a:&E{i}_A716,p716_s:&E{i}_S716,o40a:{a[40]},o40s:{s[40]},o716a:{a[716]},o716s:{s[716]},o717a:{a[717]},o717s:{s[717]},last_a:{a[729]},last_s:{s[729]}}},\n"
r+=r'''];
fn emp_lane(id:u8)->Option<&'static EmpLane>{if id<EMP_FIRST_ID{return None} EMP_LANES.get((id-EMP_FIRST_ID)as usize)}
pub fn empirical_has_pre(p:u8,r:u8)->bool{EMP_LANES.iter().any(|x|x.pre_proto==p&&x.pre_rot==r)}
pub fn empirical_post(id:u8)->Option<(u8,u8,u16,u8)>{emp_lane(id).map(|x|(x.post_proto,x.post_rot,x.source,x.route))}
fn edist(a:u32,b:u32)->u32{b.wrapping_sub(a)&0x3fff}
fn esafe(i:u32)->bool{for s in [8u32,9,0x562,0x563,0x22b5,0x22b6]{if edist(i&0x3fff,s)<730{return false}}true}
pub fn empirical_window_safe(ai:u32,si:u32)->bool{esafe(ai)&&esafe(si)}
fn emp_pre(p:u8,r:u8)->Option<&'static EmpLane>{EMP_LANES.iter().find(|x|x.pre_proto==p&&x.pre_rot==r)}
pub fn evaluate_empirical(proto:u8,rot:u8,state:u16,div:u16,ai:u32,si:u32)->Option<Prediction>{
 if !empirical_window_safe(ai,si){return None} let l=emp_pre(proto,rot)?;let av=(div>>8)as u8;let sv=div as u8;
 let pre=apply_sums(state,l.full_a[av as usize],l.full_s[sv as usize]);let la=av.wrapping_add(l.last_a);let ls=sv.wrapping_add(l.last_s);let(mut support,mut mask,mut raw)=(0u8,0u8,0u16);
 if l.route==3{for i in 0..5usize{let mut st=pre;let mut q=[0u8;3];for j in 0..3{st=upd(st,la.wrapping_add(DEEP_A[i][j]),ls.wrapping_add(DEEP_S[i][j]));q[j]=st as u8}if q[0]>=0xc0{continue}let v=((q[1]as u16)<<8)|q[2]as u16;if shiny(v){support=support.saturating_add(DEEP_WEIGHT[i]);mask|=1<<i;if raw==0{raw=v}}}if support<MIN_SUPPORT_WEIGHT{return None}}
 else{let mut st=pre;let mut q=[0u8;4];for j in 0..4{st=upd(st,la.wrapping_add(EMP_R4_A[j]),ls.wrapping_add(EMP_R4_S[j]));q[j]=st as u8}if q[0]<0xc0{return None}let v=((q[2]as u16)<<8)|q[3]as u16;if !shiny(v){return None}support=4;mask=1;raw=v}
 let s40=apply_sums(state,l.p40_a[av as usize],l.p40_s[sv as usize]);let d40=((av.wrapping_add(l.o40a)as u16)<<8)|sv.wrapping_add(l.o40s)as u16;
 let s716=apply_sums(state,l.p716_a[av as usize],l.p716_s[sv as usize]);let d716=((av.wrapping_add(l.o716a)as u16)<<8)|sv.wrapping_add(l.o716s)as u16;
 let d717=((av.wrapping_add(l.o717a)as u16)<<8)|sv.wrapping_add(l.o717s)as u16;let s717=upd(s716,(d717>>8)as u8,d717 as u8);
 Some(Prediction{lane_id:l.id,source:l.source,support_weight:support,shiny_mask:mask,raw,expected40_state:s40,expected40_div:d40,expected716_state:s716,expected716_div:d716,expected717_state:s717,expected717_div:d717})}
'''
P.write_text(P.read_text()+r)
t=T.read_text()
t=rep(t,'    practical_live_exact_eval: u32,\n    practical_post_proto: u8,','    practical_live_exact_eval: u32,\n    practical_empirical: bool,\n    practical_empirical_eval: u32,\n    practical_empirical_cell_frames: u32,\n    practical_empirical_skip_exception: u32,\n    practical_empirical_candidates: u32,\n    practical_learn: u8,\n    practical_post_proto: u8,','fields')
t=rep(t,'            practical_live_exact_eval: 0,\n            practical_post_proto: 0,','            practical_live_exact_eval: 0,\n            practical_empirical: false,\n            practical_empirical_eval: 0,\n            practical_empirical_cell_frames: 0,\n            practical_empirical_skip_exception: 0,\n            practical_empirical_candidates: 0,\n            practical_learn: 0,\n            practical_post_proto: 0,','defaults')
t=rep(t,'        self.practical_live_exact_eval = 0;\n        self.practical_post_proto = 0;','        self.practical_live_exact_eval = 0;\n        self.practical_empirical = false;\n        self.practical_empirical_eval = 0;\n        self.practical_empirical_cell_frames = 0;\n        self.practical_empirical_skip_exception = 0;\n        self.practical_empirical_candidates = 0;\n        self.practical_learn = 0;\n        self.practical_post_proto = 0;','reset')
s=t.index('    fn live_practical_lane(&self) -> Option<u8> {');e=t.index('\n    fn bind_practical_prediction',s)
t=t[:s]+'''    fn live_pre_cell(&self)->Option<(u8,u8)>{let r=latest_pre_vblank_ring();let n=(r.count as usize).min(PRE_VBLANK_RING_LEN);if n!=PRE_VBLANK_RING_LEN{return None}let(last,_)=pre_ring_sample(&r,n-1);let lag=rng_advance().wrapping_sub(last);if lag>1{return None}let(p,mut rot,best,_,ok)=classify_pre_ring(&r);if !ok||best!=0{return None}if lag==1{rot=rot.wrapping_add(1)&15}Some((p,rot))}\n    fn live_practical_lane(&self)->Option<u8>{let(p,r)=self.live_pre_cell()?;practical::lane_for_pre(p,r)}\n'''+t[e:]
a='    fn practical_wait_monitor(&mut self, reader: &Gen2Reader) {'
t=rep(t,a,"    fn enter_stage3_learn(&mut self,p:u8,r:u8){if p==b'D'&&r==15{self.practical_learn=1;self.practical_active=false;self.practical_candidate_valid=false;self.practical_empirical=false;self.practical_miss=0;self.practical_post_proto=p;self.practical_post_rot=r;self.practical_terminal_advance=0;}}\n\n"+a,'learn')
s=t.index(a);e=t.index('\n    fn practical_fail',s)
t=t[:s]+'''    fn practical_wait_monitor(&mut self,reader:&Gen2Reader){
 if !self.practical_search_enabled||!self.practical_live_scan||self.probe_session||self.practical_active||self.practical_candidate_valid{return}let cur=rng_advance();if cur==self.practical_live_last_advance{return}self.practical_live_last_advance=cur;self.practical_live_checked=self.practical_live_checked.saturating_add(1);
 let Some((proto,rot))=self.live_pre_cell()else{self.practical_live_no_lane=self.practical_live_no_lane.saturating_add(1);return};let proven=practical::lane_for_pre(proto,rot);let emp=practical::empirical_has_pre(proto,rot);if proven.is_some(){self.practical_live_lane_frames=self.practical_live_lane_frames.saturating_add(1)}if emp{self.practical_empirical_cell_frames=self.practical_empirical_cell_frames.saturating_add(1)}if proven.is_none()&&!emp{self.practical_live_no_lane=self.practical_live_no_lane.saturating_add(1);return}
 let Some(ai0)=add_div_tracker().index()else{self.practical_live_index_wait=self.practical_live_index_wait.saturating_add(1);return};let Some(si0)=sub_div_tracker().index()else{self.practical_live_index_wait=self.practical_live_index_wait.saturating_add(1);return};let ai=(ai0 as u32)&0x3fff;let si=(si0 as u32)&0x3fff;let state=reader.rng_state();let div=measured_div();
 if let Some(id)=proven{self.practical_live_exact_eval=self.practical_live_exact_eval.saturating_add(1);if let Some(x)=practical::evaluate_exact(id,state,div,ai,si){self.practical_live_found_advance=cur;self.practical_live_found_state=state;self.practical_live_found_div=div;self.practical_live_found_lane=id;self.practical_live_found_tick=pnp::system_tick();self.practical_live_found_ai=ai;self.practical_live_found_si=si;self.practical_live_scan=false;self.practical_search_enabled=false;self.clear_transport_diag();self.bind_practical_prediction(x);self.practical_empirical=false;pnp::request_pause();return}}
 if emp{if !practical::empirical_window_safe(ai,si){self.practical_empirical_skip_exception=self.practical_empirical_skip_exception.saturating_add(1);return}self.practical_empirical_eval=self.practical_empirical_eval.saturating_add(1);if let Some(x)=practical::evaluate_empirical(proto,rot,state,div,ai,si){self.practical_empirical_candidates=self.practical_empirical_candidates.saturating_add(1);self.practical_live_found_advance=cur;self.practical_live_found_state=state;self.practical_live_found_div=div;self.practical_live_found_lane=x.lane_id;self.practical_live_found_tick=pnp::system_tick();self.practical_live_found_ai=ai;self.practical_live_found_si=si;self.practical_live_scan=false;self.practical_search_enabled=false;self.clear_transport_diag();self.bind_practical_prediction(x);self.practical_empirical=true;pnp::request_pause();return}}
 }
'''+t[e:]
s=t.index('        if self.practical_active {\n            let e = self.entries[self.len - 1];');e=t.index('\n        if self.probe_active && window[2] == SUICUNE_SPECIES {',s)
t=t[:s]+'''        if self.practical_active{let e=self.entries[self.len-1];let rel=e.advance.wrapping_sub(self.probe_target.advance).wrapping_sub(1);let mut fail=0u8;
 if self.practical_empirical{if rel==40&&!self.practical_checked40{self.practical_checked40=true;let post=classify_post_entries(self.entries,self.len,self.probe_target.advance);if post.valid{self.practical_post_proto=post.proto;self.practical_post_rot=post.rot40;self.practical_post_score=post.best_score}let ok=if let Some((p,r,_,_))=practical::empirical_post(self.practical_lane){post.valid&&post.best_score==0&&post.proto==p&&post.rot40==r}else{false};if !ok||e.state!=self.practical_expected40_state||e.div!=self.practical_expected40_div{if post.valid&&post.best_score==0&&post.proto==b'D'&&post.rot40==15{self.enter_stage3_learn(post.proto,post.rot40)}else{self.practical_fail(1)}return}}else if rel==716&&!self.practical_checked716{self.practical_checked716=true;if e.state!=self.practical_expected716_state||e.div!=self.practical_expected716_div{fail=2}}else if rel==717&&!self.practical_checked717{self.practical_checked717=true;if e.state!=self.practical_expected717_state||e.div!=self.practical_expected717_div{fail=3}}}
 else{if rel==40&&!self.practical_checked40{self.practical_checked40=true;if e.state!=self.practical_expected40_state||e.div!=self.practical_expected40_div{let post=classify_post_entries(self.entries,self.len,self.probe_target.advance);if post.valid{self.practical_post_proto=post.proto;self.practical_post_rot=post.rot40;self.practical_post_score=post.best_score}if post.valid&&post.best_score==0&&post.proto==b'D'&&post.rot40==15{self.enter_stage3_learn(post.proto,post.rot40);return}if post.valid&&post.best_score==0{if let Some(id)=practical::lane_for_post_unique(post.proto,post.rot40){let Some(ai)=add_div_tracker().index()else{self.practical_fail(1);return};let Some(si)=sub_div_tracker().index()else{self.practical_fail(1);return};if let Some(x)=practical::evaluate_post_exact(id,e.state,e.div,(ai as u32)&0x3fff,(si as u32)&0x3fff){self.rebind_practical_post_v690(x,post.proto,post.rot40)}else{self.practical_fail(1);return}}else{self.practical_fail(1);return}}else{self.practical_fail(1);return}}}else if rel==716&&!self.practical_checked716{self.practical_checked716=true;if e.state!=self.practical_expected716_state||e.div!=self.practical_expected716_div{fail=2}}else if rel==717&&!self.practical_checked717{self.practical_checked717=true;if e.state!=self.practical_expected717_state||e.div!=self.practical_expected717_div{fail=3}}}if fail!=0{self.practical_fail(fail);return}}
'''+t[e:]
t=rep(t,'            let _ = write!(\n                line,\n                "BRANCH700,V700,{},{:02X},{},{},{},{},{},{},{}\\n",','            let _=write!(line,"STAGE3,V710,{},{},{},{},{},{},{},{},{},{:02X},{},{:04X}\\n",self.practical_empirical as u8,self.practical_empirical_cell_frames,self.practical_empirical_eval,self.practical_empirical_skip_exception,self.practical_empirical_candidates,self.practical_learn,self.practical_live_found_lane,self.practical_live_found_ai,self.practical_live_found_si,self.practical_post_proto,self.practical_post_rot,self.practical_raw);pnp::trace_file_write(line.as_bytes());line.clear();\n            let _ = write!(\n                line,\n                "BRANCH710,V710,{},{:02X},{},{},{},{},{},{},{}\\n",','telemetry')
t=t.replace('"S700 ','"S710 ')
t=rep(t,'pnp::println!("S710 READY UP+B L{} W{} {:04X}", self.practical_lane, self.practical_support, self.practical_raw);','if self.practical_empirical{pnp::println!("S710 READY UP+B E{} W{} {:04X}",self.practical_source,self.practical_support,self.practical_raw)}else{pnp::println!("S710 READY UP+B L{} W{} {:04X}",self.practical_lane,self.practical_support,self.practical_raw)}','ready')
t=rep(t,'        } else if self.probe_session && self.probe_active && !self.practical_active {\n            pnp::println!("S658 TEST");','        }else if self.practical_learn==1&&self.probe_session&&self.probe_active{pnp::println!("S710 LEARN D15");\n        } else if self.probe_session && self.probe_active && !self.practical_active {\n            pnp::println!("S658 TEST");','learnui')
t=rep(t,'        } else if self.practical_active {\n            pnp::println!("S710 PATH L{} W{}", self.practical_lane, self.practical_support);','        }else if self.practical_active&&self.practical_empirical{pnp::println!("S710 EPATH E{} W{}",self.practical_source,self.practical_support);\n        } else if self.practical_active {\n            pnp::println!("S710 PATH L{} W{}", self.practical_lane, self.practical_support);','pathui')
t=rep(t,'                    "S710 SCAN A{} C{} L{} I{} E{}",\n                    rng_advance().wrapping_sub(self.practical_live_start_advance),\n                    self.practical_live_checked,\n                    self.practical_live_lane_frames,\n                    self.practical_live_index_wait,\n                    self.practical_live_exact_eval\n                );','                    "S710 SCAN A{} C{} P{} X{} I{} E{}",\n                    rng_advance().wrapping_sub(self.practical_live_start_advance),self.practical_live_checked,self.practical_live_lane_frames,self.practical_empirical_eval,self.practical_live_index_wait,self.practical_live_exact_eval\n                );','scanui')
T.write_text(t)
print('Applied Suicune v7.1 Stage3')
