#!/usr/bin/env python3
from pathlib import Path
import re

TRACE=Path('reader_core/src/crystal/trace.rs')
PRACTICAL=Path('reader_core/src/crystal/practical.rs')
INPUT=Path('reader_core/src/pnp/input.rs')
BIND=Path('reader_core/src/pnp/bindings.rs')
MAIN=Path('3gx/sources/main.c')

def need(s,m,label):
    if m not in s: raise SystemExit(f'v718 missing {label}: {m}')

def rust_span(s, signature):
    start=s.find(signature)
    if start<0: raise SystemExit(f'v718 missing fn {signature}')
    b=s.find('{',start); depth=0
    for i in range(b,len(s)):
        if s[i]=='{': depth+=1
        elif s[i]=='}':
            depth-=1
            if depth==0:
                e=i+1
                while e<len(s) and s[e] in ' \t': e+=1
                if e<len(s) and s[e]=='\n': e+=1
                return start,e
    raise SystemExit(f'v718 unclosed fn {signature}')

def drop_rust_fn(s, signature):
    a,b=rust_span(s,signature); return s[:a]+s[b:]

def c_block_span(s, signature):
    start=s.find(signature)
    if start<0: raise SystemExit(f'v718 missing C block {signature}')
    b=s.find('{',start); depth=0
    for i in range(b,len(s)):
        if s[i]=='{': depth+=1
        elif s[i]=='}':
            depth-=1
            if depth==0:
                e=i+1
                while e<len(s) and s[e] in ' \t': e+=1
                if e<len(s) and s[e]=='\n': e+=1
                return start,e
    raise SystemExit(f'v718 unclosed C block {signature}')

# practical.rs: delete the v6.7 future/open-loop search model. Full-index
# cadence helpers used by current exact evaluators remain.
p=PRACTICAL.read_text()
for m in ['pub const SEARCH_HORIZON: u32 = 12000;', 'pub const MIN_SEARCH_LEAD: u32 = 180;',
          'pub const ROLL_REFRESH_INTERVAL: u32 = 256;', 'pub const ROLL_LOCK_LEAD: u32 = 384;',
          'pub const MAX_SEARCH_CANDIDATES: usize = 8;', 'pub fn has_proto(proto: u8) -> bool',
          'pub fn normal_step(state: &mut u16, div: &mut u16, ai: &mut u32, si: &mut u32)']:
    need(p,m,m)
p=re.sub(r'^pub const SEARCH_HORIZON:.*\n(?:\/\/ v6\.6\.0.*\n)?pub const MIN_SEARCH_LEAD:.*\npub const ROLL_REFRESH_INTERVAL:.*\npub const ROLL_LOCK_LEAD:.*\npub const MAX_SEARCH_CANDIDATES:.*\n','',p,flags=re.M)
p=drop_rust_fn(p,'pub fn has_proto(proto: u8) -> bool')
p=drop_rust_fn(p,'pub fn normal_step(state: &mut u16, div: &mut u16, ai: &mut u32, si: &mut u32)')
p=p.replace('// Generated by apply_suicune_practical_shiny_v64.py.\n// Known pre-stop1 donor lanes are joined to the clean no-R stop2=717 tail\n// measured in trace0096. Runtime candidate scoring is O(1).',
'''// Suicune Stage3 runtime model.\n// Current hardware state/DIV/index is evaluated at each actionable live root.\n// No future-target queue, open-loop transport, or rolling future search exists here.''')
p=p.replace('long WAIT transport','current exact-index cadence')
PRACTICAL.write_text(p)

# Rust host API: delete the inactive neutral-delay experiment end-to-end.
i=INPUT.read_text(); need(i,'/// Suicune v6.1 input-neutral pre-execution delay metrics.','delay metrics')
a=i.find('/// Suicune v6.1 input-neutral pre-execution delay metrics.')
fs=i.find('pub fn suicune_delay_metrics()',a); _,e=rust_span(i[fs:],'pub fn suicune_delay_metrics()')
e=fs+e
while e<len(i) and i[e] in ' \t\n': e+=1
i=i[:a]+i[e:]; INPUT.write_text(i)

b=BIND.read_text(); need(b,'host_suicune_delay_profile_used','delay bindings')
ls=b.splitlines(True); out=[]; n=0
while n<len(ls):
    if n+1<len(ls) and '#[no_mangle]' in ls[n] and 'host_suicune_delay_' in ls[n+1]: n+=2; continue
    if 'host_suicune_delay_' in ls[n]: n+=1; continue
    out.append(ls[n]); n+=1
BIND.write_text(''.join(out))

# C host: remove neutral-delay state/actuator and obsolete Y+B/Y+X Suicune
# command paths. Generic trace and generic Fixed-frame controls are preserved.
m=MAIN.read_text()
need(m,'// Suicune Neutral Delay Actuator v6.1.','neutral delay C')
a=m.find('// Suicune Neutral Delay Actuator v6.1.'); e=m.find('// Suicune Resume Phase Lock v4.9.',a)
m=m[:a]+m[e:]
m=m.replace('''        if ((held & (KEY_Y | KEY_B)) != (KEY_Y | KEY_B))\n        {\n            suicune_delay_chord_latched = false;\n        }\n\n''','')
if '        if (suicune_delay_pending)\n' in m:
    a,e=c_block_span(m,'        if (suicune_delay_pending)\n'); m=m[:a]+m[e:]
marker='''                arm_suicune_probe();\n                if (held & KEY_DUP)\n                {\n                    if (suicune_delay_ready)'''
need(m,marker,'UP+B delay bookkeeping')
a=m.find('                    if (suicune_delay_ready)',m.find(marker))
stop=m.find('                    suicune_observe_reset();',a)
if stop<0: raise SystemExit('v718 missing observe reset after delay bookkeeping')
m=m[:a]+m[stop:]
sig='            if ((held & KEY_B) && !suicune_delay_chord_latched && !(held & KEY_DUP))'
need(m,sig,'legacy Y+B delay command'); a,e=c_block_span(m,sig); m=m[:a]+m[e:]
cs=m.find('            // Y + X arms Suicune Deep Probe')
need(m,'            // Y + X arms Suicune Deep Probe','legacy Y+X comment')
a,e=c_block_span(m,'            if (just_pressed & KEY_X)')
m=m[:cs]+m[e:]
m=m.replace('// Requiring !Y preserves the legacy Y+B neutral-delay command.','// Require !Y so B cannot overlap the Y-command namespace.')
m=m.replace('// v6.4 practical shiny future search/cancel.','// Stage3 current-root live scan start.')
m=m.replace('// Y+X is pressed; while paused it becomes a stable display-cycle anchor.','// the Exact-2F command; while paused it becomes a stable display-cycle anchor.')
m=m.replace('''            // v5.6: S00/P00 remain fixed. E is selected automatically\n            // when Y+X arms the trial (A=E07, B=E08, C=E09). D-pad input is\n            // deliberately ignored here so pause-screen redraw timing cannot\n            // create a hidden configuration mismatch.\n''','''            // Current Stage3 uses the calibrated zero resume/start phase slots.\n            // D-pad input does not alter those timing slots.\n''')
m=m.replace('            // Y + B arms and disarms. While armed, A does not resume.\n','')
m=m.replace('// Suicune Early Control Lab v5.5. E controls the single critical transition\n// immediately after the 13th repeated rel26. OFF leaves the transition natural\n// but still logs it, so baseline and controlled trials use the same build.',
'''// Suicune rel26 timing-compat telemetry.\n// IMPORTANT: the old Early Control/parity hypothesis is rejected. Control is\n// permanently OFF. This workload is retained only because the current donor\n// corpus was captured with these rel26 measurements present.''')
m=m.replace('// v6.0: the parity selector was falsified by 0067-0071. Use the slot\n    // already latched at Y+X from the six-run calibration sequence.',
'''// Historical profile bookkeeping is telemetry/timing compatibility only.\n    // It does not select or predict a current Stage3 branch.''')
MAIN.write_text(m)

# trace.rs: remove dead queue/transport/rolling state and unreachable WAIT/error
# UI; retain current-root evaluation, CrossBranch, LearnAllPost, final guards and
# timing-sensitive rel26 observation workload.
t=TRACE.read_text()
for m0 in ['practical_search_count','practical_transport_reason','practical_roll_next','practical_targets','fn rolling_refresh_targets','TRANSPORT,V670','S717 WAIT']:
    need(t,m0,m0)
t=t.replace('practical_search_enabled','practical_scan_enabled').replace('reset_scan_epoch_v716','reset_scan_epoch')
dead=['practical_search_count','practical_search_index','practical_search_error','practical_search_skipped',
      'practical_transport_reason','practical_transport_target','practical_transport_pred_state','practical_transport_pred_div',
      'practical_transport_actual_state','practical_transport_actual_div','practical_transport_actual_lane',
      'practical_roll_next','practical_roll_count','practical_roll_eval','practical_roll_pre','practical_roll_refresh_fail',
      'practical_search_from','practical_targets','practical_states','practical_divs','practical_lanes','practical_supports','practical_raws']
ls=t.splitlines(True); out=[]
for line in ls:
    s=line.strip()
    if any(re.match(rf'{re.escape(n)}\s*:',s) for n in dead): continue
    out.append(line)
t=''.join(out)
newscan='''    pub fn search_practical_targets(&mut self, _reader: &Gen2Reader) {\n        self.reset_scan_epoch();\n        self.practical_terminal_advance = 0;\n        self.practical_candidate_valid = false;\n        self.practical_active = false;\n        self.practical_miss = 0;\n        self.practical_live_scan = true;\n        self.practical_live_start_advance = rng_advance();\n        self.practical_live_start_tick = pnp::system_tick();\n        self.practical_post_proto = 0;\n        self.practical_post_rot = 0;\n        self.practical_post_score = 0xffff;\n        self.practical_rebound = false;\n\n        // v7.1.8: actual-root scan only. There is no future target queue,\n        // search horizon, rolling re-root transport, or open-loop wait.\n        self.practical_scan_enabled = true;\n        pnp::request_release_resume();\n    }\n'''
a,e=rust_span(t,'    pub fn search_practical_targets(&mut self, _reader: &Gen2Reader)'); t=t[:a]+newscan+t[e:]
for line in ['        self.practical_search_error = 0;\n','        self.practical_search_skipped = 0;\n','        self.practical_search_count = 0;\n','        self.practical_search_index = 0;\n','        self.clear_transport_diag();\n','        self.practical_roll_next = 0;\n']:
    t=t.replace(line,'')
for sig in ['    fn clear_transport_diag(&mut self)','    fn set_transport_diag(','    fn save_transport_diag(&mut self)','    fn rolling_refresh_targets(&mut self, reader: &Gen2Reader) -> bool']:
    if sig in t: t=drop_rust_fn(t,sig)
t=t.replace('self.clear_transport_diag();','')
draw=t.find('pub fn draw_rng_status'); a=t.find('        if self.practical_scan_enabled {',draw); e=t.find('        } else if self.practical_candidate_valid',a)
if a<0 or e<0: raise SystemExit('v718 scan UI boundary missing')
scanui='''        if self.practical_scan_enabled {\n            pnp::println!("S718 SCAN");\n            pnp::println!("FR{} ADV{}", self.practical_live_checked, rng_advance().wrapping_sub(self.practical_live_start_advance));\n            pnp::println!("P{} X{}", self.practical_live_lane_frames, self.practical_empirical_cell_frames);\n            pnp::println!("EV{} SK{}", self.practical_live_exact_eval.saturating_add(self.practical_empirical_eval), self.practical_live_index_wait.saturating_add(self.practical_empirical_skip_exception));\n'''
t=t[:a]+scanui+t[e:]
t=t.replace('"S717 ','"S718 ').replace('"S658 TEST"','"S718 TEST NO READY"')
t=re.sub(r'\s*\} else if self\.practical_search_error != 0 \{\n\s*pnp::println!\("S718 RESET RECOMMENDED"\);\n\s*pnp::println!\("WHY E\{\}", self\.practical_search_error\);\n\s*pnp::println!\("R > VC RESET"\);','',t,count=1)
t=t.replace('pnp::println!("R > VC RESET");','pnp::println!("RESET VC MANUALLY");')
tele=t.find('            let _ = write!(\n                line,\n                "transport,version,reason,search_from,target,current,search_count')
if tele<0: raise SystemExit('v718 transport telemetry start missing')
p64=t.find('"PRACTICAL,V64',tele); end=t.find('            );',p64)+len('            );')
if p64<0 or end<0: raise SystemExit('v718 old PRACTICAL telemetry end missing')
newtel='''            let _ = write!(line, "practical,version,candidate,active,target,lane,source,support_weight,shiny_mask,pred_raw,miss,check40,check716,check717,exp40_state,exp40_div,exp716_state,exp716_div,exp717_state,exp717_div\\n");\n            pnp::trace_file_write(line.as_bytes());\n            line.clear();\n            let _ = write!(line, "PRACTICAL,V718,{},{},{},{},{},{},{},{:04X},{},{},{},{},{:04X},{:04X},{:04X},{:04X},{:04X},{:04X}\\n\\n",\n                self.practical_candidate_valid as u8, self.practical_active as u8, self.practical_target, self.practical_lane,\n                self.practical_source, self.practical_support, self.practical_mask, self.practical_raw, self.practical_miss,\n                self.practical_checked40 as u8, self.practical_checked716 as u8, self.practical_checked717 as u8,\n                self.practical_expected40_state, self.practical_expected40_div, self.practical_expected716_state,\n                self.practical_expected716_div, self.practical_expected717_state, self.practical_expected717_div);'''
t=t[:tele]+newtel+t[end:]
a=t.find('        let dm = pnp::suicune_delay_metrics();')
if a>=0:
    e=t.find('        let stale_age =',a)
    if e<0: raise SystemExit('v718 delay telemetry end missing')
    t=t[:a]+t[e:]
draw=t.find('pub fn draw_rng_status'); a=t.find('        let fixed = pnp::fixed_a_frame();',draw); e=t.find('        if self.endpoint.capture_advance != 0 {',a)
if a>=0 and e>=0: t=t[:a]+t[e:]
t=t.replace('/// True from Y+X until a non-probe Trace explicitly replaces this session.','/// True from the current UP+B Exact-2F arm until a non-probe Trace replaces the session.')
t=t.replace('// v5.5 Early Control Lab. These are reset only when Y+X arms a fresh\n    // Suicune probe; start() calls reset() again and must not erase them.','// Timing-compat observation retained because current donor/model data was captured\n    // with this rel20..35 instrumentation active. It does not choose a branch.')
t=t.replace('/// Called directly from the C pause loop by Y+X.  Because this runs while','/// Called directly from the C pause loop by the current UP+B command. Because this runs while')
t=t.replace('// Y+X is handled directly by the C pause loop, so synchronize all','// The Exact-2F arm is handled directly by the C pause loop, so synchronize all')
t=t.replace('// A new Fixed run without a fresh Y+X is a legacy trace, not a','// A new generic Fixed run without a fresh Suicune arm is a legacy trace, not a')
t=t.replace('// complete, preserve the exact Y+X Target so a failed/mis-armed trial','// complete, preserve the exact frozen-root Target so a failed/mis-armed trial')
TRACE.write_text(t)

joined='\n'.join([TRACE.read_text(),PRACTICAL.read_text(),INPUT.read_text(),BIND.read_text(),MAIN.read_text()])
for bad in ['SEARCH_HORIZON','MIN_SEARCH_LEAD','ROLL_REFRESH_INTERVAL','ROLL_LOCK_LEAD','MAX_SEARCH_CANDIDATES','rolling_refresh_targets','TRANSPORT,V670','ROLL,V671','suicune_delay_','S718 WAIT','R > VC RESET']:
    if bad in joined: raise SystemExit(f'v718 forbidden legacy marker remains: {bad}')
for good in ['S718 SCAN','S718 READY UP+B','RESET VC MANUALLY','PRACTICAL,V718','fn practical_wait_monitor','fn rebind_known_post_v713','fn enter_stage3_learn','FASTTAIL715,V715','practical::evaluate_exact','practical::evaluate_empirical']:
    if good not in joined: raise SystemExit(f'v718 required current marker missing: {good}')
print('Applied Suicune v7.1.8 cleanup: dead future transport and neutral-delay paths removed; current-root/CrossBranch/Learn/guards retained')
