#!/usr/bin/env python3
from pathlib import Path
P=Path('reader_core/src/crystal/practical.rs'); T=Path('reader_core/src/crystal/trace.rs')
p=P.read_text(); t=T.read_text()
def need(s,x,label):
    if x not in s: raise SystemExit('missing '+label)
def forbid(s,x,label):
    if x in s: raise SystemExit('forbidden '+label)
need(p,'const EMP_COUNT: usize = 5;','five empirical profiles')
for src in (98,99,100,101,104): need(p,f'source:{src},',f'empirical source {src}')
for cell in ("pre_proto:b'A',pre_rot:10","pre_proto:b'D',pre_rot:12","pre_proto:b'B',pre_rot:11","pre_proto:b'A',pre_rot:6","pre_proto:b'B',pre_rot:1"): need(p,cell,'PRE-conditioned cell '+cell)
need(p,'pub fn empirical_window_safe','empirical full-index safety gate')
need(p,'pub fn evaluate_empirical','empirical O(1) evaluator')
need(p,'if lows[0]>=0xc0 { continue; }','route3 decision gate')
need(p,'if lows[0]<0xc0 { return None; }','route4 decision gate')
need(p,'const EMP_R4_A:[u8;4]=[183,185,191,193];','measured route4 tail')
need(p,'pub fn evaluate_exact','v7 proven exact evaluator retained')
need(p,'pub fn evaluate_post_exact','v7 exact rebind retained')
need(t,'fn live_pre_cell(&self) -> Option<(u8,u8)>','all PRE cells observable')
need(t,'let proven_lane=practical::lane_for_pre(proto,rot);','proven lane priority')
need(t,'let empirical_cell=practical::empirical_has_pre(proto,rot);','empirical PRE filter')
need(t,'if let Some(pred)=practical::evaluate_empirical(proto,rot,state,div,ai,si)','empirical scan')
need(t,'self.practical_empirical_skip_exception','exception skip telemetry')
need(t,'post.proto==pp && post.rot40==rr','actual POST guard')
need(t,'e.state!=self.practical_expected40_state || e.div!=self.practical_expected40_div','rel40 state/div guard')
need(t,'e.state!=self.practical_expected716_state || e.div!=self.practical_expected716_div','rel716 guard')
need(t,'e.state!=self.practical_expected717_state || e.div!=self.practical_expected717_div','rel717 guard')
need(t,'fn enter_stage3_learn','D15 learn path')
need(t,"post.proto==b'D' && post.rot40==15",'D15 trigger')
need(t,'S710 LEARN D15','D15 UI')
need(t,'S710 READY UP+B E{}','empirical READY')
need(t,'S710 EPATH E{}','empirical path UI')
need(t,'S710 SCAN A{} C{} P{} X{} I{} E{}','scan telemetry UI')
need(t,'STAGE3,V710','stage3 CSV')
need(t,'BRANCH710,V710','branch CSV version')
need(t,'S658 TEST','fast validate preserved')
forbid(t,'S700 ','stale v700 UI')
forbid(p,'WIDE_PROFILE_COUNT','old all-root 14-profile scan')
print('v7.1 audit PASS: PRE-conditioned recent profiles + exception safety + route gates + rel40/716/717 hard guards + D15 learning')
