#!/usr/bin/env python3
from pathlib import Path
p=Path('reader_core/src/crystal/practical.rs').read_text()
t=Path('reader_core/src/crystal/trace.rs').read_text()
def need(s,x,label):
    if x not in s: raise SystemExit('missing '+label)
def forbid(s,x,label):
    if x in s: raise SystemExit('forbidden '+label)
need(p,'EMP_COUNT:usize=5','five empirical profiles')
for src in (98,99,100,101,104): need(p,f'source:{src},',f'source {src}')
for cell in ("pre_proto:b'A',pre_rot:10","pre_proto:b'D',pre_rot:12","pre_proto:b'B',pre_rot:11","pre_proto:b'A',pre_rot:6","pre_proto:b'B',pre_rot:1"): need(p,cell,'PRE cell '+cell)
need(p,'post_proto:b\'C\',post_rot:8','C/r8 branch')
need(p,'post_proto:b\'C\',post_rot:2','C/r2 branch')
need(p,'route:4','route4 branch')
need(p,'pub fn empirical_window_safe','full-index safety')
need(p,'pub fn evaluate_empirical','empirical evaluator')
need(p,'q[0]>=0xc0{continue}','route3 decision')
need(p,'q[0]<0xc0{return None}','route4 decision')
need(p,'const EMP_R4_A:[u8;4]=[183,185,191,193]','measured route4 tail')
need(p,'pub fn evaluate_exact','proven exact retained')
need(p,'pub fn evaluate_post_exact','post exact retained')
need(t,'fn live_pre_cell(&self)->Option<(u8,u8)>','live PRE cell')
need(t,'let proven=practical::lane_for_pre(proto,rot)','proven priority')
need(t,'let emp=practical::empirical_has_pre(proto,rot)','empirical PRE conditioning')
need(t,'practical::evaluate_empirical(proto,rot,state,div,ai,si)','empirical live evaluation')
need(t,'self.practical_empirical_skip_exception','exception telemetry')
need(t,'post.proto==p&&post.rot40==r','actual POST identity guard')
need(t,'e.state!=self.practical_expected40_state||e.div!=self.practical_expected40_div','rel40 state/div guard')
need(t,'e.state!=self.practical_expected716_state||e.div!=self.practical_expected716_div','rel716 guard')
need(t,'e.state!=self.practical_expected717_state||e.div!=self.practical_expected717_div','rel717 guard')
need(t,'fn enter_stage3_learn','learn path')
need(t,"post.proto==b'D'&&post.rot40==15",'D15 learn trigger')
need(t,'S710 LEARN D15','D15 UI')
need(t,'S710 READY UP+B E{}','empirical READY')
need(t,'S710 EPATH E{}','empirical path')
need(t,'S710 SCAN A{} C{} P{} X{} I{} E{}','scan UI')
need(t,'STAGE3,V710','stage3 telemetry')
need(t,'BRANCH710,V710','branch telemetry')
need(t,'S658 TEST','fast validate retained')
forbid(t,'S700 ','stale v700 status')
forbid(p,'WIDE_PROFILE_COUNT','old 14-profile global scan')
print('v7.1 CI audit PASS: recent PRE-conditioned branches + route gates + full-index safety + hard guards + D15 learning')
