#!/usr/bin/env python3
import argparse
from pathlib import Path

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('model'); ap.add_argument('out'); a=ap.parse_args()
    model=Path(a.model).read_text()
    html=r'''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Suicune Prototype v3.9</title>
<style>
:root{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#111;background:#f5f5f7}body{margin:0}.wrap{max-width:1180px;margin:auto;padding:20px}.card{background:white;border:1px solid #ddd;border-radius:14px;padding:16px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px}label{font-size:12px;color:#555}input,select,button{width:100%;box-sizing:border-box;padding:10px;border:1px solid #bbb;border-radius:9px;background:#fff;font-size:15px}button{font-weight:700;cursor:pointer}.row{display:flex;gap:8px}.row>*{flex:1}table{width:100%;border-collapse:collapse;font-size:13px}th,td{border-bottom:1px solid #eee;padding:8px;text-align:right}th:first-child,td:first-child{text-align:left}.ok{color:#087a33;font-weight:700}.sh{font-weight:800;color:#9a0070}.small{font-size:12px;color:#666}.status{padding:10px;background:#f2f2f2;border-radius:9px;margin-top:10px;white-space:pre-wrap}.bad{color:#b00020}.scroll{overflow:auto;max-height:65vh}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}</style></head><body><div class="wrap">
<h1>スイクン Prototype / Rotation v3.9</h1><p>4 prototype + rotation を基準に、0066〜0079の実測branchを同時評価します。</p>
<div class="card"><b>入力</b><div class="grid"><div><label>State (hex)</label><input id="state" value="2735"></div><div><label>DIV (hex)</label><input id="div" value="F2F2"></div><div><label>ADIV</label><input id="adiv" value="10016"></div><div><label>SDIV</label><input id="sdiv" value="9303"></div><div><label>Start Advance</label><input id="start" value="6600"></div><div><label>検索数</label><input id="count" value="50000"></div><div><label>最大表示</label><input id="max" value="100"></div><div><label>位相モデル</label><select id="phaseMode"><option value="exact">OBSERVED exact phase</option><option value="diff">同じdiff class（探索）</option></select></div><div><label>フィルタ</label><select id="filter"><option value="any">ANY: 1 branch以上色</option><option value="all">適用branchすべて色</option><option value="multi">2 branch以上色</option><option value="p2">2 prototype以上で色</option></select></div></div><div class="row" style="margin-top:10px"><button id="search">色違い候補を検索</button><button id="cancel">停止</button></div><div id="status" class="status">待機中</div></div>
<div class="card"><b>既知Traceをロード</b><div id="samples" class="grid"></div></div><div class="card"><b>モデル状態</b><div id="modelInfo"></div><div id="selftest" class="status"></div></div><div class="card"><b>候補</b><div class="scroll"><table><thead><tr><th>Target</th><th>State</th><th>DIV</th><th>proto any</th><th>proto robust</th><th>shiny/applicable</th><th>A</th><th>B</th><th>C</th><th>D</th><th>予測DV</th></tr></thead><tbody id="out"></tbody></table></div></div></div><script>
const MODEL=__MODEL__;
const INC=[0x12,0x12,0x12,0x13,0x12,0x12,0x13,0x12,0x12,0x13,0x12,0x12,0x13,0x12,0x12,0x13];
const wrap8=x=>x&255,hx=(x,w=4)=>(x>>>0).toString(16).toUpperCase().padStart(w,'0');
function parseHex(id){const s=document.getElementById(id).value.trim().replace(/^0x/i,'');if(!/^[0-9a-f]+$/i.test(s))throw Error(id+' の16進数を確認');return parseInt(s,16)&0xffff}function dec(id,min,max){const n=Number(document.getElementById(id).value);if(!Number.isInteger(n)||n<min||n>max)throw Error(id+' の値を確認');return n}function params(){return{state:parseHex('state'),div:parseHex('div'),ai:dec('adiv',0,16383),si:dec('sdiv',0,16383),start:dec('start',0,1e9),count:dec('count',1,1e6),max:dec('max',1,1000)}}
function divDelta(i,k){let full=Math.floor(k/16),rem=k%16,total=full*296;for(let t=0;t<rem;t++)total+=INC[(i+t)&15];return total&255}function nextRoot(r){let av=wrap8(r.av+INC[r.ai&15]),sv=wrap8(r.sv+INC[r.si&15]);r.ai=(r.ai+1)&16383;r.si=(r.si+1)&16383;let z=r.ra+av,c=z>255?1:0;r.ra=z&255;r.rs=wrap8(r.rs-sv-c);r.av=av;r.sv=sv}function makeRoot(p){return{ra:p.state>>>8,rs:p.state&255,av:p.div>>>8,sv:p.div&255,ai:p.ai,si:p.si}}function stateOf(r){return(r.ra<<8)|r.rs}function divOf(r){return(r.av<<8)|r.sv}
function shiny(raw){const a=(raw>>>12)&15,d=(raw>>>8)&15,s=(raw>>>4)&15,c=raw&15;return d===10&&s===10&&c===10&&[2,3,6,7,10,11,14,15].includes(a)}function lowerBound(a,x){let l=0,h=a.length;while(l<h){let m=(l+h)>>1;if(a[m]<x)l=m+1;else h=m}return l}function makeSidePrefix(profile,side,phase,upto){let vals=[INC[phase&15]];const f=profile.flat;for(let j=0;j<upto;j++){const i=j*4,k=f[i+(side==='A'?0:2)],res=f[i+(side==='A'?1:3)];vals.push(wrap8(divDelta(phase,k)+res))}vals.sort((a,b)=>a-b);let sum=0;for(const v of vals)sum+=v;return{vals,sum,n:vals.length}}function prepProfile(p){p.cache={A1:[],A2:[],S1:[],S2:[]};for(let ph=0;ph<16;ph++){p.cache.A1[ph]=makeSidePrefix(p,'A',ph,p.n1);p.cache.A2[ph]=makeSidePrefix(p,'A',ph,p.n2);p.cache.S1[ph]=makeSidePrefix(p,'S',ph,p.n1);p.cache.S2[ph]=makeSidePrefix(p,'S',ph,p.n2)}return p}const PROFILES=MODEL.profiles.map(prepProfile);function sumWithBase(x,base){const ge=x.vals.length-lowerBound(x.vals,256-base);return x.sum+x.n*base-256*ge}function pred(r,p){const a1=sumWithBase(p.cache.A1[r.ai&15],r.av),a2=sumWithBase(p.cache.A2[r.ai&15],r.av),s1=sumWithBase(p.cache.S1[r.si&15],r.sv),s2=sumWithBase(p.cache.S2[r.si&15],r.sv);const d1=wrap8(r.rs-s1-Math.floor((r.ra+a1)/256)),d2=wrap8(r.rs-s2-Math.floor((r.ra+a2)/256));return(d1<<8)|d2}
function profilesFor(r,mode){const a=r.ai&15,s=r.si&15;if(mode==='exact')return PROFILES.filter(p=>p.phase_a===a&&p.phase_s===s);const d=(a-s)&15;return PROFILES.filter(p=>((p.phase_a-p.phase_s)&15)===d)}function evalRoot(r,mode){const by={A:[],B:[],C:[],D:[]};let total=0,sh=0;for(const p of profilesFor(r,mode)){const raw=pred(r,p),is=shiny(raw);by[p.prototype].push({p,raw,is});total++;if(is)sh++}let any=0,robust=0;for(const k of 'ABCD'){const g=by[k];if(g.some(x=>x.is))any++;if(g.length&&g.every(x=>x.is))robust++}return{by,total,sh,any,robust}}function keep(e,f){if(!e.total)return false;if(f==='any')return e.sh>0;if(f==='all')return e.sh===e.total;if(f==='multi')return e.sh>=2;if(f==='p2')return e.any>=2;return false}function cell(g){const n=g.filter(x=>x.is).length;return`<span class="${n?'sh':''}">${n}/${g.length}</span>`}function dvs(e){let x=[];for(const k of 'ABCD')for(const q of e.by[k])if(q.is)x.push(`${k}r${q.p.rotation}:${q.p.source}=${hx(q.raw)}`);return x.slice(0,8).join(' ')+(x.length>8?' …':'')}
let cancel=false;async function search(){const st=document.getElementById('status');let p;try{p=params()}catch(e){st.textContent=e.message;st.className='status bad';return}cancel=false;const f=document.getElementById('filter').value,phaseMode=document.getElementById('phaseMode').value;let r=makeRoot(p),rows=[],sc=0;const t0=performance.now();for(let t=p.start;t<p.start+p.count&&!cancel;t++){const e=evalRoot(r,phaseMode);if(keep(e,f))rows.push({t,state:stateOf(r),div:divOf(r),e});nextRoot(r);sc++;if((sc&2047)===0){st.textContent=`${sc.toLocaleString()} / ${p.count.toLocaleString()}  候補 ${rows.length}`;await new Promise(requestAnimationFrame)}}rows.sort((a,b)=>b.e.robust-a.e.robust||b.e.any-a.e.any||b.e.sh-a.e.sh||a.t-b.t);const total=rows.length;if(rows.length>p.max)rows.length=p.max;document.getElementById('out').innerHTML=rows.map(x=>`<tr><td>${x.t}</td><td class=mono>${hx(x.state)}</td><td class=mono>${hx(x.div)}</td><td>${x.e.any}/4</td><td>${x.e.robust}/4</td><td>${x.e.sh}/${x.e.total}</td>${'ABCD'.split('').map(k=>`<td>${cell(x.e.by[k])}</td>`).join('')}<td class="mono small">${dvs(x.e)}</td></tr>`).join('');st.className='status ok';st.textContent=`${cancel?'停止':'完了'} ${sc.toLocaleString()} advances / 条件一致 ${total} / ${(performance.now()-t0).toFixed(0)} ms`}document.getElementById('search').onclick=search;document.getElementById('cancel').onclick=()=>cancel=true;
function loadSample(p){document.getElementById('state').value=p.target_state;document.getElementById('div').value=p.target_div;document.getElementById('adiv').value=p.target_adiv;document.getElementById('sdiv').value=p.target_sdiv;document.getElementById('start').value=p.target}document.getElementById('samples').innerHTML=PROFILES.map((p,i)=>`<button data-i=${i}>${p.source} P${p.prototype} r${p.rotation} ${p.fp_score}/16</button>`).join('');document.getElementById('samples').onclick=e=>{if(e.target.dataset.i!=null)loadSample(PROFILES[+e.target.dataset.i])};function selftest(){let pass=0,lines=[];for(const p of PROFILES){const r={ra:parseInt(p.target_state,16)>>>8,rs:parseInt(p.target_state,16)&255,av:parseInt(p.target_div,16)>>>8,sv:parseInt(p.target_div,16)&255,ai:p.target_adiv,si:p.target_sdiv};const got=pred(r,p),ok=got===parseInt(p.raw_dv,16);if(ok)pass++;else lines.push(`${p.source}: ${hx(got)} != ${p.raw_dv}`)}document.getElementById('selftest').className='status '+(pass===PROFILES.length?'ok':'bad');document.getElementById('selftest').textContent=`Exact replay regression ${pass}/${PROFILES.length}`+(lines.length?'\n'+lines.join('\n'):'')}const counts={};for(const p of PROFILES)counts[p.prototype]=(counts[p.prototype]||0)+1;document.getElementById('modelInfo').innerHTML=`model <b>${MODEL.version}</b> · profiles ${PROFILES.length} · A/B/C/D=${['A','B','C','D'].map(k=>counts[k]||0).join('/')} · local windows ${MODEL.local_windows.map(x=>x.join('-')).join(', ')}<br><span class=small>exact phaseではADIV&15 / SDIV&15が一致したprofileだけを適用します。diff modeは探索用です。</span>`;selftest();
</script></body></html>'''.replace('__MODEL__',model)
    Path(a.out).write_text(html)
    print('wrote',a.out)
if __name__=='__main__':main()
