name: Lint, Test, Build

on:
  pull_request:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  lint-test-build:
    name: Lint, test, and build
    runs-on: ubuntu-latest
    container: zaksabeast/devkitarm-rust
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint
        run: make lint
      - name: Reset after lint
        run: |
          git -c safe.directory="$GITHUB_WORKSPACE" reset --hard HEAD
          git -c safe.directory="$GITHUB_WORKSPACE" clean -fd
      - name: Test
        run: make test
      - name: Reset after test
        run: |
          git -c safe.directory="$GITHUB_WORKSPACE" reset --hard HEAD
          git -c safe.directory="$GITHUB_WORKSPACE" clean -fd
      - name: Build
        run: make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PokeReader-Blue-Legend-v8.4.1-Articuno-Auto
          retention-days: 3
          path: out/default.3gx
