name: Lint, Test, Build

on:
  pull_request:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  lint-test-build:
    name: Lint, test, and build
    runs-on: ubuntu-latest
    container: zaksabeast/devkitarm-rust
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint
        run: make lint
      - name: Reset generated sources after lint
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git reset --hard HEAD
          git clean -fdx
      - name: Test
        run: make test
      - name: Reset generated sources after test
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git reset --hard HEAD
          git clean -fdx
      - name: Build
        run: make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PokeReader-Blue-Legend-v8.4.4-Articuno-ColdNPC2
          retention-days: 3
          path: out/default.3gx
